<?php

declare(strict_types=1);

namespace Maetva\ESeason\WebCampServices;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'BankAcct' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\BankAcct',
            'Cash' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Cash',
            'DirectBill' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\DirectBill',
            'LoyaltyRedemption' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\LoyaltyRedemption',
            'MiscChargeOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\MiscChargeOrder',
            'MultimediaObjectType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\MultimediaObjectType',
            'PaymentCardType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\PaymentCardType',
            'DueDatePayment' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\DueDatePayment',
            'PaymentFormType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\PaymentFormType',
            'Voucher' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Voucher',
            'Ancv' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Ancv',
            'SelectPlace' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SelectPlace',
            'Camping' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Camping',
            'ChannelInformation' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ChannelInformation',
            'DelayedPaymentType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\DelayedPaymentType',
            'Context' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Context',
            'CustomerListInformation' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\CustomerListInformation',
            'CustomerOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\CustomerOrder',
            'FriendOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\FriendOrder',
            'CustomerOptin' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\CustomerOptin',
            'GeographicalArea' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\GeographicalArea',
            'OpenPeriod' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\OpenPeriod',
            'IdStay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\IdStay',
            'IdProduct' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\IdProduct',
            'IdTariffProduct' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\IdTariffProduct',
            'IdPaymentType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\IdPaymentType',
            'OrderLine' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\OrderLine',
            'PaymentInformation' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\PaymentInformation',
            'Product' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Product',
            'Season' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Season',
            'OptinContext' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\OptinContext',
            'OptinQuestionContext' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\OptinQuestionContext',
            'CategoryType' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\CategoryType',
            'CategSelectPlace' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\CategSelectPlace',
            'SectorCom' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SectorCom',
            'Criterion' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Criterion',
            'OpeningPeriods' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\OpeningPeriods',
            'GPSCoordinates' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\GPSCoordinates',
            'SearchPlace' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SearchPlace',
            'BoolAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\BoolAvailability',
            'BoolCategAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\BoolCategAvailability',
            'Stay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Stay',
            'PromoInfo' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\PromoInfo',
            'StayDeposit' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\StayDeposit',
            'Sharegroop' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Sharegroop',
            'Promo' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Promo',
            'Supplement' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Supplement',
            'SupplementFilled' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SupplementFilled',
            'SupplementIncluded' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SupplementIncluded',
            'Rubrics' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Rubrics',
            'TariffProduct' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\TariffProduct',
            'Order' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Order',
            'PlaceInfo' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\PlaceInfo',
            'Vehicle' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\Vehicle',
            'DayStock' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\DayStock',
            'RebookingSetting' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RebookingSetting',
            'ExternalCriterion' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ExternalCriterion',
            'SpecificParam' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\SpecificParam',
            'RequestCpgAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgAvailability',
            'RequestCpgAvailabilityNoPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgAvailabilityNoPrice',
            'RequestCpgAvailableCEStock' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgAvailableCEStock',
            'RequestCpgSimpleSearch' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgSimpleSearch',
            'RequestCpgBoolAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgBoolAvailability',
            'RequestCpgBoolCategAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgBoolCategAvailability',
            'RequestCpgContext' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgContext',
            'RequestCpgOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgOrder',
            'RequestCpgMultiOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgMultiOrder',
            'RequestCpgChangeOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgChangeOrder',
            'RequestCpgOrderStatus' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgOrderStatus',
            'RequestCpgPayment' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgPayment',
            'RequestCpgMultiPayment' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgMultiPayment',
            'RequestCpgPaymentStatus' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgPaymentStatus',
            'RequestCpgPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgPrice',
            'RequestCpgUnitPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgUnitPrice',
            'RequestCpgPlaceList' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgPlaceList',
            'RequestCpgFavorites' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgFavorites',
            'RequestCpgGetSupplementsForOneStay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgGetSupplementsForOneStay',
            'ResponseCpgAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgAvailability',
            'ResponseCpgAvailableCEStock' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgAvailableCEStock',
            'ResponseCpgBoolAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgBoolAvailability',
            'ResponseCpgBoolCategAvailability' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgBoolCategAvailability',
            'ResponseCpgContext' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgContext',
            'ResponseCpgOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgOrder',
            'ResponseCpgMultiOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgMultiOrder',
            'ResponseCpgChangeOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgChangeOrder',
            'ResponseCpgOrderStatus' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgOrderStatus',
            'ResponseCpgPayment' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgPayment',
            'ResponseCpgMultiPayment' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgMultiPayment',
            'ResponseCpgPaymentStatus' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgPaymentStatus',
            'ResponseCpgPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgPrice',
            'ResponseCpgUnitPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgUnitPrice',
            'ResponseCpgChangeOrderPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgChangeOrderPrice',
            'ResponseCpgPlaceList' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgPlaceList',
            'ResponseCpgSimpleSearch' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgSimpleSearch',
            'ResponseCpgFavorites' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgFavorites',
            'RequestCpgGetIdOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgGetIdOrder',
            'ResponseCpgGetIdOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgGetIdOrder',
            'RequestCpgChangeOrderPrice' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgChangeOrderPrice',
            'RequestCpgCancel' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgCancel',
            'ResponseCpgCancel' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgCancel',
            'RequestCpgConfirmOrCancelOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgConfirmOrCancelOrder',
            'ResponseCpgConfirmOrCancelOrder' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgConfirmOrCancelOrder',
            'RequestCpgDayStock' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgDayStock',
            'ResponseCpgDayStock' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgDayStock',
            'RequestCpgCheckStay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgCheckStay',
            'ResponseCpgCheckStay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgCheckStay',
            'ResponseCpgGetSupplementsForOneStay' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgGetSupplementsForOneStay',
            'RequestCpgCancelInsurances' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgCancelInsurances',
            'ResponseCpgCancelInsurances' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgCancelInsurances',
            'RequestCpgArrivalDate' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\RequestCpgArrivalDate',
            'ResponseCpgArrivalDate' => '\\Maetva\\ESeason\\WebCampServices\\StructType\\ResponseCpgArrivalDate',
        ];
    }
}
